package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildConfC'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildConfC")) {
    expectSteps {
        script {
            name = "Step 1"
            scriptContent = """
                mkdir output
                echo "Create Installer.exe" > output/Installer.exe
            """.trimIndent()
        }
        script {
            name = "Echo token"
            scriptContent = "echo %myToken% > token.txt"
        }
    }
    steps {
        insert(2) {
            script {
                name = "UI step"
                scriptContent = """echo "added from UI""""
            }
        }
    }
}
