package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildConfC'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildConfC")) {
    expectSteps {
        script {
            name = "Step 1"
            scriptContent = """
                mkdir output
                echo "Create Installer.exe" > output/Installer.exe
            """.trimIndent()
        }
        script {
            name = "Step 2"
            scriptContent = """echo "This is the second step.""""
        }
        script {
            name = "Step 3"
            scriptContent = """echo "This is the thrid step.""""
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            executionMode = BuildStep.ExecutionMode.RUN_ON_SUCCESS
            clearConditions()
        }
    }
}
