package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildConfA'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildConfA")) {
    expectSteps {
        script {
            id = "RUNNER_1"
            scriptContent = "sleep %SleepDuration%"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            id = "RUNNER_1"
            clearConditions()
            scriptContent = """
                sleep %SleepDuration%
                echo "this chage was made through UI 4"
            """.trimIndent()
        }
    }
}
