package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'SettingsRootCopy'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("SettingsRootCopy")
    name = "settings-root-copy"
    url = "git@github.com:tolache/versioned-settings.git"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        userName = "git"
        uploadedKey = "github.pem"
    }
}))

