package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'VersionedSettingsCopy'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("VersionedSettingsCopy")) {
    val expected = GitVcsRoot({
        id("VersionedSettingsCopy")
        name = "versioned-settings-copy"
        url = "https://github.com/tolache/versioned-settings"
        branch = "refs/heads/master"
        authMethod = password {
            userName = "tolache"
            password = "credentialsJSON:7d8cca8e-bc35-4156-a965-0b32123691bc"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branchSpec = "refs/heads/*"
    }

}
